/* The following code was generated by JFlex 1.6.0 */

/*
 *  Copyright (C) 2018 JPEXS, All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */
package com.jpexs.graphs.graphviz.dot.parser;
import java.util.Stack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>D:/Dropbox/Programovani/JavaSE/graphs/lexers/dot.flex</tt>
 */
public final class DotLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int HTML = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\46\1\47\1\1\22\0\1\3\1\0\1\45"+
    "\7\0\1\5\1\0\1\34\1\10\1\11\1\4\12\7\1\42\1\33"+
    "\1\44\1\37\1\43\2\0\1\22\1\32\1\20\1\25\1\30\1\6"+
    "\1\21\1\24\1\17\4\6\1\26\1\27\1\23\1\6\1\15\1\13"+
    "\1\14\1\31\5\6\1\40\1\50\1\41\1\0\1\6\1\0\1\22"+
    "\1\32\1\20\1\25\1\30\1\6\1\21\1\24\1\17\4\6\1\26"+
    "\1\27\1\23\1\6\1\15\1\13\1\14\1\31\5\6\1\35\1\0"+
    "\1\36\7\0\1\46\252\0\2\16\115\0\1\12\200\0\u0178\6\u1cb0\0"+
    "\1\46\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\1\1\4\1\5\3\1"+
    "\5\4\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\2\22\1\23\1\21"+
    "\1\24\1\25\1\3\1\0\1\5\1\26\1\0\1\27"+
    "\2\0\3\4\1\0\3\4\1\30\2\3\4\0\3\4"+
    "\1\0\3\4\3\0\3\4\1\0\1\4\1\31\1\32"+
    "\2\0\2\4\1\33\1\0\1\4\1\34\1\0\1\34"+
    "\1\4\1\0\1\4\1\0\1\4\2\35\2\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\173\0\315\0\366"+
    "\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215\0\u023e"+
    "\0\u0267\0\u0290\0\173\0\173\0\173\0\173\0\173\0\173"+
    "\0\173\0\173\0\173\0\173\0\173\0\173\0\u02b9\0\173"+
    "\0\173\0\u02e2\0\173\0\173\0\u030b\0\u0334\0\u019a\0\173"+
    "\0\u019a\0\173\0\u035d\0\u0386\0\u03af\0\u03d8\0\u0401\0\u042a"+
    "\0\u0453\0\u047c\0\u04a5\0\173\0\u04ce\0\173\0\u04f7\0\u0520"+
    "\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f\0\u0668"+
    "\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e\0\u0787\0\u07b0"+
    "\0\u07d9\0\u011f\0\u011f\0\u0802\0\u082b\0\u0854\0\u087d\0\u011f"+
    "\0\u08a6\0\u08cf\0\173\0\u08f8\0\u011f\0\u0921\0\u094a\0\u0973"+
    "\0\u099c\0\u09c5\0\173\0\u011f\0\173\0\u011f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\4\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\2\11\1\4\2\11\1\17"+
    "\3\11\1\20\1\21\1\11\1\22\2\11\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\4\1\33"+
    "\1\34\1\35\1\7\1\4\1\36\1\37\1\40\42\36"+
    "\1\41\2\35\1\42\1\36\1\37\1\40\40\36\1\43"+
    "\1\44\1\36\2\35\1\36\53\0\1\6\51\0\1\7"+
    "\43\0\1\7\5\0\1\45\1\46\51\0\2\11\3\0"+
    "\3\11\1\0\14\11\25\0\1\12\1\0\1\47\46\0"+
    "\1\12\1\50\1\51\31\0\1\52\14\0\1\47\55\0"+
    "\1\53\14\0\1\54\25\0\2\11\3\0\1\11\1\55"+
    "\1\11\1\0\12\11\1\56\1\11\24\0\2\11\3\0"+
    "\2\11\1\57\1\0\14\11\24\0\2\11\3\0\3\11"+
    "\1\60\1\61\13\11\24\0\2\11\3\0\3\11\1\0"+
    "\10\11\1\62\3\11\24\0\2\11\3\0\3\11\1\0"+
    "\6\11\1\63\5\11\20\0\1\40\113\0\1\64\3\0"+
    "\1\45\1\65\1\66\46\45\5\67\1\70\43\67\15\0"+
    "\1\71\65\0\1\72\24\0\2\11\3\0\2\11\1\73"+
    "\1\0\14\11\24\0\2\11\3\0\3\11\1\0\13\11"+
    "\1\74\24\0\2\11\3\0\3\11\1\0\3\11\1\75"+
    "\10\11\37\0\1\76\35\0\2\11\3\0\3\11\1\0"+
    "\2\11\1\77\11\11\24\0\2\11\3\0\3\11\1\0"+
    "\6\11\1\100\5\11\24\0\2\11\3\0\3\11\1\0"+
    "\2\11\1\101\11\11\20\0\1\66\46\0\5\67\1\102"+
    "\43\67\4\0\1\66\1\70\61\0\2\103\52\0\1\104"+
    "\35\0\2\11\3\0\3\11\1\103\1\105\13\11\24\0"+
    "\2\11\3\0\3\11\1\0\2\11\1\106\11\11\24\0"+
    "\2\11\3\0\3\11\1\0\4\11\1\107\7\11\33\0"+
    "\1\110\41\0\2\11\3\0\2\11\1\111\1\0\14\11"+
    "\24\0\2\11\3\0\3\11\1\0\11\11\1\112\2\11"+
    "\24\0\2\11\3\0\3\11\1\0\11\11\1\113\2\11"+
    "\16\0\4\67\1\66\1\102\43\67\20\0\1\114\45\0"+
    "\1\115\41\0\2\11\3\0\3\11\1\0\1\11\1\116"+
    "\12\11\24\0\2\11\3\0\2\11\1\117\1\0\14\11"+
    "\24\0\2\11\3\0\3\11\1\0\5\11\1\120\6\11"+
    "\40\0\1\121\34\0\2\11\3\0\3\11\1\0\3\11"+
    "\1\122\10\11\32\0\1\123\56\0\1\124\34\0\2\11"+
    "\3\0\1\11\1\125\1\11\1\0\14\11\24\0\2\11"+
    "\3\0\3\11\1\0\3\11\1\126\10\11\41\0\1\127"+
    "\33\0\2\11\3\0\3\11\1\0\4\11\1\130\7\11"+
    "\41\0\1\131\33\0\2\11\3\0\3\11\1\0\4\11"+
    "\1\132\7\11\42\0\1\133\32\0\2\11\3\0\3\11"+
    "\1\0\5\11\1\134\6\11\42\0\1\135\32\0\2\11"+
    "\3\0\3\11\1\0\5\11\1\136\6\11\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2542];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\14\1\14\11\1\1\2\11"+
    "\1\1\2\11\1\1\1\0\1\1\1\11\1\0\1\11"+
    "\2\0\3\1\1\0\3\1\1\11\1\1\1\11\4\0"+
    "\3\1\1\0\3\1\3\0\3\1\1\0\3\1\2\0"+
    "\3\1\1\0\1\1\1\11\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

    StringBuilder string = new StringBuilder();
    boolean finish = false;
    boolean parameter = false;
    String parameterName = null;
    int tagLevel = 0;
    boolean printLexed = false;

    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */
    public DotLexer() {

    }

    public void setPrintLexed(boolean printLexed)
    {
        this.printLexed = printLexed;
    }

    public int yychar() {
        return yychar;
    }

    public int yyline() {
        return yyline + 1;
    }

    private final Stack<DotParsedSymbol> pushedBack = new Stack<>();
   
    public void pushback(DotParsedSymbol symb) {
        pushedBack.push(symb);
        last = null;
    }

    DotParsedSymbol last;
    public DotParsedSymbol lex() throws java.io.IOException, DotParseException{
        DotParsedSymbol ret = null;
        if (!pushedBack.isEmpty()){
            ret = last = pushedBack.pop();
        } else {
            ret = last = yylex();
        }
        if(printLexed)
        {
            System.out.println("LEX:"+ret);
        }
        return ret;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DotLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public DotParsedSymbol yylex() throws java.io.IOException, DotParseException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_INVALID_SYMBOL, yytext());
          }
        case 31: break;
        case 2: 
          { yyline++;
          }
        case 32: break;
        case 3: 
          { /*ignore*/
          }
        case 33: break;
        case 4: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_ID, DotParsedSymbol.IDTYPE_IDENTIFIER, yytext());
          }
        case 34: break;
        case 5: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_ID, DotParsedSymbol.IDTYPE_NUMERAL, yytext());
          }
        case 35: break;
        case 6: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_SEMICOLON, yytext());
          }
        case 36: break;
        case 7: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_COMMA, yytext());
          }
        case 37: break;
        case 8: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_BRACE_OPEN, yytext());
          }
        case 38: break;
        case 9: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_BRACE_CLOSE, yytext());
          }
        case 39: break;
        case 10: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_EQUAL, yytext());
          }
        case 40: break;
        case 11: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_BRACKET_OPEN, yytext());
          }
        case 41: break;
        case 12: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_BRACKET_CLOSE, yytext());
          }
        case 42: break;
        case 13: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_COLON, yytext());
          }
        case 43: break;
        case 14: 
          { string.setLength(0);
                                     tagLevel = 1;
                                     yybegin(HTML);
          }
        case 44: break;
        case 15: 
          { string.setLength(0);
                                     yybegin(STRING);
          }
        case 45: break;
        case 16: 
          { 
          }
        case 46: break;
        case 17: 
          { string.append(yytext());
          }
        case 47: break;
        case 18: 
          { yyline++; string.append(yytext());
          }
        case 48: break;
        case 19: 
          { yybegin(YYINITIAL);
                                     // length also includes the trailing quote
                                     return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_ID, DotParsedSymbol.IDTYPE_DOUBLE_QUOTED, string.toString());
          }
        case 49: break;
        case 20: 
          { tagLevel--;                                     
                                    if(tagLevel == 0){
                                        yybegin(YYINITIAL);
                                        return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_ID, DotParsedSymbol.IDTYPE_HTML_STRING, string.toString());
                                    }else{
                                        string.append(yytext());
                                    }
          }
        case 50: break;
        case 21: 
          { tagLevel++; 
                                    string.append(yytext());
          }
        case 51: break;
        case 22: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_MINUSMINUS, yytext());
          }
        case 52: break;
        case 23: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_ARROW, yytext());
          }
        case 53: break;
        case 24: 
          { string.append('\"');
          }
        case 54: break;
        case 25: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_NODE, yytext());
          }
        case 55: break;
        case 26: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_EDGE, yytext());
          }
        case 56: break;
        case 27: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_GRAPH, yytext());
          }
        case 57: break;
        case 28: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_STRICT, yytext());
          }
        case 58: break;
        case 29: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_DIGRAPH, yytext());
          }
        case 59: break;
        case 30: 
          { return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_KEYWORD_SUBGRAPH, yytext());
          }
        case 60: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return new DotParsedSymbol(yyline(), DotParsedSymbol.TYPE_EOF, yytext());
            }
            case 95: break;
            default:
              {
                return null;
              }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
